name: web_demo
description: A new Flutter project.

publish_to: "none" 

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  get_it: ^7.2.0
  line_icons: ^2.0.1
  oktoast: ^3.2.0
  responsive_builder: ^0.7.0
  markdown_widget: ^2.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.10
  go_router: ^7.1.1
  shared_preferences: ^2.1.0
  appwrite: ^9.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_native_splash: ^2.2.19
  flutter_easyloading: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/wechat_cobe.jpeg
    - assets/images/logo.png
    - assets/images/dark_logo.png
    - assets/images/wechat_mini.jpg


flutter_native_splash:
  color: "#ffffff" # 你想要的背景色
  image: assets/images/splash_logo.png # 你的启动屏幕图片路径
  android: true
  ios: true
  web: true
