name: web_demo
description: A new Flutter project.

publish_to: "none" 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.1.1
  provider: ^6.0.3
  get_it: ^7.2.0
  line_icons: ^2.0.1
  oktoast: ^3.2.0
  responsive_builder: ^0.6.4
  markdown_widget: ^2.1.0
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.10
  go_router: ^6.5.7
  shared_preferences: ^2.1.0
  appwrite: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/wechat_cobe.jpeg
    - assets/images/logo.png
    - assets/images/dark_logo.png
    - assets/images/wechat_mini.jpg
